### ISSUE TITLE
API keys in querystrings?

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/ietf-at#21]
The docs currently say:
```
apikeystring | API Key (can be submitted as query string)
```
Is that really true?

**Comment by kesara** [comment]
This is true.
For example following query works:
```
# as query string
curl https://author-tools.ietf.org/api/render/text?apikey=foobar -F 'file=@./foobar.xml'
# as form parameter
curl https://author-tools.ietf.org/api/render/text -F 'apikey=foobar' -F 'file=@./foobar.xml'
```

**Comment by rjsparks** [comment]
Does it _need_ to be true? That will cause keys to end up in httpd logs.

**Comment by kesara** [comment]
Good point. This doesn't have to be this way. API keys were allowed in query strings to mimic how datatracker API handle requests.
I'll change Author Tools API to not to accept API key as query string.
