### ISSUE TITLE
Mysterious missing newlines in rfcdiff?

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-tools/ietf-at#289]
### Describe the issue

@mengelbart and I submitted https://datatracker.ietf.org/doc/draft-ietf-avtcore-rtp-over-quic/ a few minutes ago. 

When we look at https://author-tools.ietf.org/iddiff?url2=draft-ietf-avtcore-rtp-over-quic-02, we see several places where we have added text that included a end of line/newline, which looks fine in the HTML version at https://www.ietf.org/archive/id/draft-ietf-avtcore-rtp-over-quic-02.html, but doesn't show as a space between paragraphs in the diff (see Sections 1, 1.2, 1.3, 2, and 5.1). I also noticed just now that the same thing is happening in the References section. 

I don't THINK this is something we did (it is happening with text from different PRs that both Mathis and I submitted), and I'm even more confused, because it's not happening **every** time we added text at the end of a paragraph (see new text in 5.3, first paragraph).

And I also noticed just now that the same thing is happening in the References section, and all of those new references should be generated from kramdown, I think. 

I apologize for asking that this bug report be prioritized, but the new draft will be presented at AVTCORE on Thursday 23 February, and we'll be asking people to **look at the diffs**. :yum: :stuck_out_tongue_closed_eyes:

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@SpencerDawkins, A fix for the missing new lines issue has been deployed on author tools.

**Comment by SpencerDawkins** [comment]
@kesara - thank you!
