### ISSUE TITLE
Low priority IETF Author tools problem with xml2rfc

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/ietf-at#300]
### Describe the issue

From Joel Halpern:

Subject: 	Low priority IETF Author tools problem
Date: 	Wed, 8 Mar 2023 22:46:25 -0500
From: 	"Joel Halpern" <jmh@joelhalpern.com>

I use the web passed xml2rfc.  Really helpful and appreciated.

I had it process my my draft, and it got an error.  It told me enough
that I could fix the error.  Again, thanks.

I then tried to hit the Text button to tell it to try again.  It
refused.  Some sort of an error fetching the file?   I reloaded the page
and was able to re-select the file and rerun teh generation.  So only a
minor problem.

Yours,

Joel

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This is the same issue reported in https://github.com/ietf-tools/ietf-at-ui/issues/43
