### ISSUE TITLE
Consider URL inputs

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/ietf-at#62]
This might come with some risks, but it might be good to allow users to specify a URL for a document.  This is a feature that I routinely use with rfcdiff, using input URLs on GitHub pages or in GitHub repositories with raw.githubusercontent.com.

**Comment by kesara** [comment]
This feature is now available on https://author-tools.ietf.org/iddiff

Example: https://author-tools.ietf.org/diff?url_1=https://www.ietf.org/archive/id/draft-ietf-tsvwg-ecn-l4s-id-20.txt&url_2=https://www.ietf.org/archive/id/draft-ietf-tsvwg-ecn-l4s-id-24.txt

Allowed domains (including subdomains) for URL inputs are:
*  ietf.org
* rfc-editor.org
* githubusercontent.com
* github.io
* gitlab.com
