### ISSUE TITLE
Unnecessary year check

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at#64]
"Error converting first draft to text: Expected  to have the current year when month is missing, but found '2021'"
This is a problem. I need to compare a version from last year with a new version, so of course last year's version has last year's date. For purposes of comparison, the date rule should not be enforced at all. I might need to compare a 2020 version with a 2021 version in 2022!

**Comment by becarpenter** [comment]
I should have mentioned that the source contains just
<date year="2021"/>
Not necessarily a good idea, but valid. Not sure at all why this is an error case rather than a warning.

**Comment by kesara** [comment]
This is an issue on xml2rfc. I have created a issue on track: https://trac.ietf.org/trac/xml2rfc/ticket/704#ticket

**Comment by kesara** [comment]
I agree that this should be a warning rather than an error.
