### ISSUE TITLE
URL not taking GitHub

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-tools/ietf-at#74]
Hi, 

The following error is displayed - 

`{"error":"github.com domain is not allowed."}`

when I try to input GitHub URL for comparison! Such as https://author-tools.ietf.org/diff?doc_1=draft-ietf-opsawg-sap-00&url_2=https://github.com/IETF-OPSAWG-WG/lxnm/raw/master/I-D-sap/draft-ietf-opsawg-sap.txt

Since a lot of development happens on GitHub in IETF (and IETF encourages it), this check on the domain seems to be a mistake

**Comment by kesara** [comment]
Thanks for the bug report.
I'll add `github.com` to the allowed domain list.
https://github.com/IETF-OPSAWG-WG/lxnm/raw/master/I-D-sap/draft-ietf-opsawg-sap.txt gets redirected to https://raw.githubusercontent.com/IETF-OPSAWG-WG/lxnm/master/I-D-sap/draft-ietf-opsawg-sap.txt

For the time being, you can use that URL.
Example: https://author-tools.ietf.org/diff?doc_1=draft-ietf-opsawg-sap-00&url_2=https://raw.githubusercontent.com/IETF-OPSAWG-WG/lxnm/master/I-D-sap/draft-ietf-opsawg-sap.txt

**Comment by kesara** [comment]
URLs from `github.com` are allowed in https://author-tools.ietf.org now.

**Comment by dhruvdhody** [comment]
Thanks Kesara!
